### ISSUE TITLE
[Feature Request] Automatically re-equip the Mark of the Champion trinket after dying

### ISSUE THREAD

**Issue by vakos1** [CosminPOP/BigWigs#5]
Both of the Mark of the Champion trinkets from Kel'Thuzad's phylactery currently have a [bug on Turtle WoW](https://github.com/slowtorta/turtlewow-bug-tracker/issues/3048) where the trinkets stops working after the player dies.

My request would be to add a new feature/module that simply un-equips and re-equips (or at least just swaps the Mark to a different trinket slot) to get the Mark trinkets working again automatically upon dying and resurrecting.

**Comment by jeanlab** [comment]
I'm not sure if this belongs in bigwigs, someone already created another addon for this feature you're asking about
https://github.com/melbaa/swapondeath
